apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: google-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:191982029618:secret:GoogleKeys-WksZfJ"
        jmesPath: 
            - path: GOOGLE_CLIENT_ID
              objectAlias: google-client-id
            - path: GOOGLE_CLIENT_SECRET
              objectAlias: google-client-secret
  secretObjects:
  - data:
    - key: google-client-id
      objectName: google-client-id
    secretName: google-client-id
    type: Opaque
  - data:
    - key: google-client-secret
      objectName: google-client-secret
      secretName: google-client-secret
    type: Opaque